### ISSUE TITLE
Map Loader

### ISSUE THREAD

**Issue by tonylindorock** [PinMeister/COMP-345-Project#11]
Implement a group of C++ classes that reads and loads a map file in the .map text file format as found in the “Domination” game source files, available at: http://domination.sourceforge.net/getmaps.shtml, The map loader must be able to read any map file available on the above web page.

All the classes/functions that you implement for this component must all reside in a single .cpp/.h file duo named MapLoader.cpp/MapLoader.h.

- [x] Map loader can read Domination map file
- [x] Map loader creates a map object as a graph data structure
- [x] Map loader should be able to read any text file (valid or invalid)
- [x] Driver (a file named MapLoaderDriver.cpp) reads many different map files, creates a graph object for the valid ones and rejects the invalid ones
