### ISSUE TITLE
 Player

### ISSUE THREAD

**Issue by miche-cho** [PinMeister/COMP-345-Project#2]
Implement a group of C++ classes that implement a Warzone player using the following design: 

The classes/functions that you implement for this component must all reside in a single .cpp/.h file duo named Player.cpp/Player.h. You must deliver a file named PlayerDriver.cpp file that creates player objects and demonstrates that the player objects indeed have the above-mentioned features.

- [x] A player owns a collection  of  territories  (see  Part  1).  
- [x] A player  owns  a  hand  of  Warzone Cards  (see  Part  5).  
- [x] A player  has  their  own list  of  orders  to  be  created  and  executed  in  the  current  turn (see  Part  3).  
- [x] Player contains methods toDefend() and toAttack() that return a list of territories that are to be defended and to be attacked, respectively.
- [x] Player contains a issueOrder() method that creates an order object and adds it to the list of orders.
- [x] Driver (PlayerDriver.cpp) creates players and demonstrates that the above features are available.
