### ISSUE TITLE
Game Engine

### ISSUE THREAD

**Issue by PinMeister** [PinMeister/COMP-345-Project#49]
Implement "GameEngine.cpp/GameEngine.h"

- [x] Game Start
- [x] Game Startup Phase

Main Game Loop:
- [x] Reinforcement Phase
- [x] Order Issuing Phase
- [ ] Order Execution Phase
