### ISSUE TITLE
Orders Issuing Phase

### ISSUE THREAD

**Issue by PinMeister** [PinMeister/COMP-345-Project#54]
Implemented in function "issueOrderPhase()" in GameEngine.cpp
Decision making implemented in function "issueOrder()" in Player.cpp
- [x] toAttack(): return list of neighbouring territories are to be attacked in priority
- [x] toDefend(): return list of neighbouring territories to be defended in priority
- [x] Issue deploy orders in the list returned by toDefend(), keep deploying until no available armies
- [x] Issue advance orders to move armies from one territory to another owned territory to defend it (using toDefend())
- [x] Issue advance orders to move armies from one territory to an enemy territory to attack it (using toAttack())
- [x] Uses one of the cards in hand to issue an order that corresponds to the card in question
