### ISSUE TITLE
Map class

### ISSUE THREAD

**Issue by PinMeister** [PinMeister/COMP-345-Project#6]
Must have all classes/functions in a single Map.cpp/Map.h file
MapDriver.cpp must contain main function

- [x] Map is implemented as a connected graph, each node is a Territory, edges represent adjacency between territories
- [x] Continents are connected subgraphs, each territory belongs to one and only one continent
- [x] Include validate() method (validate above points)
- [x] Map class can be used to represent any map graph configuration
- [x] Driver creates different map objects and checks whether they are valid or not
