### ISSUE TITLE
Player Strategy Pattern

### ISSUE THREAD

**Issue by PinMeister** [PinMeister/COMP-345-Project#80]
Implement different kinds of players that make different decisions during the issue orders phase by implementing different versions of issueOrder(), toAttack() and toDefend()

Implemented in PlayerStrategies.cpp/PlayerStrategies.h
- Player class does not have subclasses
- PlayerStrategy must not be a subclass of the player class
- Player class contains data member of type PlayerStrategy
- issueOrder(), toDefend(), toAttack() do not implement behaviour and delegate their call to the PlayerStrategy object member of the Player

Create a ConcreteStrategy class with different strategies as subclasses each with their own version of issueOrder(), toAttack() and toDefend():
- [x] HumanPlayerStrategy (human player requires user interaction to make decisions)
- [x] AggressivePlayerStrategy (reinforce strongest country, always attack with it until it can't anymore, fortifies in order to maximize aggregation of forces in one country)
- [x] BenevolentPlayerStrategy (reinforce weakest countries, never attacks, fortifies to move armies to weaker countries)
- [x] NeutralPlayerStrategy (never issues any order)

Driver:
- [x] Different players can be assigned different strategies that lead to different behaviour for using the strategy pattern
- [x] Strategy adopted by a player can be changed dynamically during gameplay
- [x] Human player makes decisions according to user interaction, computer players make decisions automatically, both implemented using the strategy pattern
