### ISSUE TITLE
Cards deck/hand

### ISSUE THREAD

**Issue by Happyduck93** [PinMeister/COMP-345-Project#9]
Cards deck/hand

Implement a group of C++ classes that implements a deck and hand of Warzone cards. Each card has a type
from: bomb, reinforcement, blockade, airlift and diplomacy. The deck must have a draw() method that allows a
player to draw a card at random from the cards remaining in the deck and place it in their hand of cards. The
cards must have a play() method that is called to play the card, which creates an order and adds it to the
player’s list of orders and then returns the card to the deck. All the classes/functions that you implement for this
component must all reside in a single .cpp/.h file duo named Cards.cpp/Cards.h. You must deliver a file
named CardsDriver.cpp file that creates a deck of Warzone cards. The driver must also create a hand object
that is filled by drawing cards from the deck. 

- [x] Deck is a finite collection of Warzone cards.

- [x] Hand is a finite collection of Warzone cards. 

- [x] Each card has a type from: spy, bomb, reinforcement, blockade, airlift, and diplomacy.

- [x] Deck has a draw() method that allows a player to draw a card at random from the cards
remaining in the deck and place it in their hand.

- [x] Each card has a play() method that enables a player to use it during game play by creating
special orders. Once a card has been played, it is removed from the hand and put back into
the deck

- [x] Driver that creates a deck of cards of all different kinds, then creates a hand object that is
filled by drawing cards from the deck, then calls the play method of all cards in the hand.
